# Quartz cron: second minute hour day-of-month month day-of-week
jobs.load.cron=0 0 * * * ?
jobs.update.cron=0 */5 * * * ?
jobs.reload.cron=0 0 2 * * ?
jobs.zone=Europe/Istanbul
quarkus.scheduler.overdue-grace-period=5M
